### ISSUE TITLE
Some Useful Tools

### ISSUE THREAD

**Issue by gaia** [ambrosus/ambrosus-node-contracts#149]
LABEL: Feedback

I attended ETH San Francisco and took note of some new tools you might find useful in your development. I suggest you at least take a look at them. Even if you might already be aware of some similar tools, a couple of them are entirely new (1st implementation of the concept).

Real time debugger: https://devpost.com/software/0xd3bu6

Contract Analytics: https://devpost.com/software/contractiq

Another gas profiler: https://devpost.com/software/solidity-profiler

Keep up the great work!

**Comment by vikrampatankar** [comment]
@gaia Thanks for the feedback. ContractIQ developer here. Do you think this kind of tool would be useful if we make it production ready ?

**Comment by gaia** [comment]
@vikrampatankar I don't know if Ambrosus will use it but I surely see an use for it, by many platforms.
